apiVersion: apps/v1
kind: Deployment
metadata:
  name: marathon-db-deployment
  labels:
    app: marathon-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marathon-db
  template:
    metadata:
      labels:
        app: marathon-db
    spec:
      containers:
        - name: db
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: marathon-configmap
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: marathon-configmap
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: marathon-db-secret
                  key: postgres-password
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: marathon-db-service
spec:
  ports:
    - port: 5432
  selector:
    app: marathon-db
  type: ClusterIP
